import { Role } from '@prisma/client';

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, string[]> = {
  SUPER_ADMIN: [
    'view:dashboard',
    'view:rooms',
    'create:rooms',
    'edit:rooms',
    'delete:rooms',
    'view:reservations',
    'create:reservations',
    'edit:reservations',
    'delete:reservations',
    'checkin:reservations',
    'checkout:reservations',
    'view:guests',
    'create:guests',
    'edit:guests',
    'delete:guests',
    'view:staff',
    'create:staff',
    'edit:staff',
    'delete:staff',
    'view:attendance',
    'manage:attendance',
    'clock:self',
    'view:pos',
    'create:pos',
    'void:pos',
    'discount:pos',
    'view:inventory',
    'create:inventory',
    'edit:inventory',
    'delete:inventory',
    'reorder:inventory',
    'view:housekeeping',
    'manage:housekeeping',
    'view:finance',
    'create:finance',
    'edit:finance',
    'delete:finance',
    'approve:finance',
    'view:reports',
    'export:reports',
    'view:mailing',
    'view:facilities',
    'create:facilities',
    'manage:facilities',
    'view:settings',
    'manage:settings',
    'view:hr',
    'manage:hr',
    'manage:permissions',
    'manage:pos'
  ],

  ADMIN: [
    'view:dashboard',
    'view:rooms',
    'create:rooms',
    'edit:rooms',
    'delete:rooms',
    'view:reservations',
    'create:reservations',
    'edit:reservations',
    'delete:reservations',
    'checkin:reservations',
    'checkout:reservations',
    'view:guests',
    'create:guests',
    'edit:guests',
    'delete:guests',
    'view:staff',
    'create:staff',
    'edit:staff',
    'delete:staff',
    'view:attendance',
    'manage:attendance',
    'clock:self',
    'view:pos',
    'create:pos',
    'void:pos',
    'discount:pos',
    'view:inventory',
    'create:inventory',
    'edit:inventory',
    'delete:inventory',
    'reorder:inventory',
    'view:housekeeping',
    'manage:housekeeping',
    'view:finance',
    'create:finance',
    'edit:finance',
    'approve:finance',
    'view:reports',
    'export:reports',
    'view:mailing',
    'view:facilities',
    'create:facilities',
    'manage:facilities',
    'view:settings',
    'manage:settings',
    'view:hr',
    'manage:hr',
    'manage:permissions',
    'manage:pos'
  ],

  MANAGER: [
    'view:dashboard',
    'view:rooms',
    'edit:rooms',
    'view:reservations',
    'create:reservations',
    'edit:reservations',
    'checkin:reservations',
    'checkout:reservations',
    'view:guests',
    'create:guests',
    'edit:guests',
    'view:staff',
    'edit:staff',
    'view:attendance',
    'manage:attendance',
    'clock:self',
    'view:pos',
    'create:pos',
    'void:pos',
    'discount:pos',
    'view:inventory',
    'create:inventory',
    'edit:inventory',
    'reorder:inventory',
    'view:housekeeping',
    'manage:housekeeping',
    'view:finance',
    'create:finance',
    'edit:finance',
    'view:reports',
    'export:reports',
    'view:facilities',
    'create:facilities',
    'manage:facilities',
    'view:settings',
    'view:hr',
    'manage:hr',
    'manage:pos',
    'view:mailing',
  ],

  RECEPTIONIST: [
    'view:dashboard',
    'view:rooms',
    'view:reservations',
    'create:reservations',
    'edit:reservations',
    'checkin:reservations',
    'checkout:reservations',
    'view:guests',
    'create:guests',
    'edit:guests',
    'clock:self',
    'view:pos',
    'create:pos',
    'view:facilities',
    'create:facilities',
  ],

  HOUSEKEEPING: [
    'view:dashboard',
    'view:rooms',
    'view:housekeeping',
    'manage:housekeeping',
    'view:facilities',
    'clock:self',
  ],

  CASHIER: [
    'view:dashboard',
    'view:pos',
    'create:pos',
    'void:pos',
    'view:finance',
    'view:facilities',
    'create:facilities',
    'clock:self',
  ],

  BARTENDER: [
    'view:dashboard',
    'view:pos',
    'create:pos',
    'view:inventory',
    'clock:self',
  ],

  STAFF: ['view:dashboard', 'clock:self'],
};

export const LOCKED_ROLES: Role[] = ['SUPER_ADMIN', 'ADMIN'];
