ALTER TYPE "HotelCronJobType" ADD VALUE IF NOT EXISTS 'HOUSEKEEPING_FOLLOW_UP_SCAN';

ALTER TABLE "Hotel"
ADD COLUMN "guestCheckoutReminderLeadDays" INTEGER[] NOT NULL DEFAULT ARRAY[1,0]::INTEGER[],
ADD COLUMN "housekeepingFollowUpEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "housekeepingFollowUpGraceHours" INTEGER NOT NULL DEFAULT 2;
